version: '3.7'

services:
  backend:
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python /code/manage.py migrate; python /code/manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks: ['mynetwork']

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks: ['mynetwork']
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    command: 'npm run dev'
    depends_on:
      - db
      - backend
    ports:
      - "8080:8080"

volumes:
  db:
networks: {mynetwork: {}}