version: '3.0'

services:
  backend:
    build: ./backend
    command: python /code/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks: ['mynetwork']

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks: ['mynetwork']

  redis:
    image: "redis:alpine"
    networks: ['mynetwork']

  celery:
    build: ./backend
    command: bash -c 'cd code/events; celery -A events worker -l info'
    depends_on:
      - db
      - redis
    networks: ['mynetwork']

  celery-beat:
    build: ./backend
    command: bash -c 'cd code/events; celery -A events beat -l info'
    depends_on:
      - db
      - redis
    networks: ['mynetwork']

  frontend:
    build: ./frontend
    command: 'npm run dev'
    depends_on:
      - db
      - backend
    ports:
      - "8080:8080"
    networks: ['mynetwork']

volumes:
  db:
networks: {mynetwork: {}}